/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.QlyNCCDao;
import Entity.QlyNCC;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.List;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class TC_NhaCungCap extends javax.swing.JPanel {

    /**
     * Creates new form TC_NhaCungCap
     */
    public TC_NhaCungCap() {
        initComponents();
        LoadData();
        SetControls();
        txtMa.setEditable(false);
        txtTen.setEditable(false);
        txtDiachi.setEditable(false);
        txtSdt.setEditable(false);
        txtEmail.setEditable(false);
        
        btnAllowAdd.setBackground(Color.orange);
        btnAllowUpdate.setBackground(Color.orange);
        btnAllowDelete.setBackground(Color.orange);
        btnThem.setBackground(Color.orange);
        btnSua.setBackground(Color.orange);
        btnXoa.setBackground(Color.orange);
        btnHuy.setBackground(Color.orange);
        
        btnThem.setVisible(false);
        btnSua.setVisible(false);
        btnXoa.setVisible(false);
        btnHuy.setVisible(false);
    }
    public void SetControls(){
        txtMa.setText("");
        txtTen.setText("");
        txtDiachi.setText("");
        txtSdt.setText("");
        txtEmail.setText("");
        fileLabel.setIcon(null);

        btnThem.setVisible(false);
        btnSua.setVisible(false);
        btnXoa.setVisible(false);
        btnHuy.setVisible(false);
        btnAllowAdd.setVisible(true);
        btnAllowUpdate.setVisible(true);
        btnAllowDelete.setVisible(true);
    }
    String selectImagePath="";
    private DefaultTableModel tableModel;
    QlyNCC ncc = new QlyNCC();
    QlyNCCDao nccDao = new QlyNCCDao();
    public void LoadData(){
        String[] columnName={"Mã ncc","Tên ncc","Địa chỉ","SDT","Email","image"};
        Vector vctHeader = new Vector();
        Vector vctData = new Vector();
        vctHeader.add("Mã ncc");
        vctHeader.add("Tên ncc");
        vctHeader.add("Địa chỉ");
        vctHeader.add("SDT");
        vctHeader.add("Email");
        vctHeader.add("image");
        List<QlyNCC> list = nccDao.getAll();
        list.stream().map((t) -> {
            Vector vector = new Vector();
            vector.add(t.getMancc());
            vector.add(t.getTenncc());
            vector.add(t.getDiachi());
            vector.add(t.getSdt());
            vector.add(t.getEmail());
            vector.add(t.getImage());
            return vector;
        }).forEachOrdered((t) -> {
            vctData.add(t);
        });
        tableModel = new DefaultTableModel(vctData,vctHeader);
        tableNcc.setModel(tableModel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        fileLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnAllowAdd = new javax.swing.JButton();
        btnAllowUpdate = new javax.swing.JButton();
        btnAllowDelete = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tableNcc = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();
        txtDiachi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        btnImage = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        jPanel9.setBackground(new java.awt.Color(255, 204, 0));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fileLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fileLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("NHÀ CUNG CẤP SẢN PHẨM");

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Thao tác : ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnHuy.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnHuy.setText("Hủy Thao Tác");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnAllowAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAllowAdd.setText("Thêm");
        btnAllowAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllowAddActionPerformed(evt);
            }
        });

        btnAllowUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAllowUpdate.setText("Sửa");
        btnAllowUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllowUpdateActionPerformed(evt);
            }
        });

        btnAllowDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAllowDelete.setText("Xóa");
        btnAllowDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllowDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(btnAllowAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAllowUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(btnAllowDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAllowAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnAllowUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAllowDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Danh sách nhà cung cấp : ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        tableNcc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableNcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNccMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(tableNcc);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel8.setText("Mã nhà cung cấp :");

        txtSdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSdtActionPerformed(evt);
            }
        });

        jLabel11.setText("Tên nhà cung cấp : ");

        jLabel12.setText("Email                     :");

        jLabel9.setText("Hotline                :");

        jLabel10.setText("Địa Chỉ               :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail)
                            .addComponent(txtTen)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiachi)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnImage.setText("Chọn Hình Ảnh Nhà Cung Cấp");
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(btnImage, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(btnImage, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(10, 10, 10)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        try {
            JFileChooser fileChooser = new JFileChooser("C:/Users/ADMIN/Documents/NetBeansProjects/BaiTapNhomJava/src");
            FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("hinh anh", "png","jpg");
            fileChooser.addChoosableFileFilter(imageFilter);
            fileChooser.setFileFilter(imageFilter);
            fileChooser.setMultiSelectionEnabled(false);
            int x = fileChooser.showOpenDialog(null);
            if(x==JFileChooser.APPROVE_OPTION){
                File f = fileChooser.getSelectedFile();
                selectImagePath = f.getAbsolutePath();
                ImageIcon ii = new ImageIcon(selectImagePath);
                Image image = ii.getImage().getScaledInstance(fileLabel.getWidth(), fileLabel.getHeight(), Image.SCALE_SMOOTH);
                fileLabel.setIcon(new ImageIcon(image));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnImageActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String maNCC = txtMa.getText();
        String tenNCC =txtTen.getText();
        String diaChi = txtDiachi.getText();
        String sdt = txtSdt.getText();
        String email = txtEmail.getText();
        String image = selectImagePath ;
        if (tenNCC!=null && !tenNCC.equals("")) {
            List<QlyNCC> listCheck = nccDao.getid(txtMa.getText());
            if(listCheck.size()>0){
                JOptionPane.showMessageDialog(null, "Mã nhà cung cấp bị trùng", "vui lòng kiểm tra lại", JOptionPane.ERROR_MESSAGE);
                txtMa.requestFocus();
            }
            else{
               if(nccDao.insert(new QlyNCC(maNCC, tenNCC, diaChi, sdt, email, image))>0) {
                    JOptionPane.showMessageDialog(null, "Thêm "+txtTen.getText()+" thành công !");
                    SetControls();
                    LoadData();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Thêm nhà cung cấp thất bại !");
                } 
            }
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Bạn phải nhập tên Nhà cung cấp!!!!");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        String maNCC = txtMa.getText();
        String tenNCC =txtTen.getText();
        String diaChi = txtDiachi.getText();
        String sdt = txtSdt.getText();
        String email = txtEmail.getText();
        String image = selectImagePath ;
        ncc = new QlyNCC(maNCC, tenNCC, diaChi, sdt, email, image);
        int tbao = JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa nhà cung cấp "+txtTen.getText() +" không", "!!!!!", JOptionPane.YES_NO_OPTION);
        if(tbao == JOptionPane.YES_OPTION){
            nccDao.update(ncc);
            JOptionPane.showMessageDialog(null, "Sửa thành công");
            SetControls();
            LoadData();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        String maNCC = txtMa.getText();
        String tenNCC =txtTen.getText();
        String diaChi = txtDiachi.getText();
        String sdt = txtSdt.getText();
        String email = txtEmail.getText();
        String image = selectImagePath ;

        ncc = new QlyNCC(maNCC, tenNCC, diaChi, sdt, email, image);
        int tbao = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa nhà cung cấp "+txtTen.getText() +" không", "!!!!!", JOptionPane.YES_NO_OPTION);
        if(tbao == JOptionPane.YES_OPTION){
            nccDao.delete(ncc);
            JOptionPane.showMessageDialog(null, "Xóa thành công");
            btnHuyActionPerformed(evt);
            SetControls();
            LoadData();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        txtMa.setText("");
        txtTen.setText("");
        txtDiachi.setText("");
        txtSdt.setText("");
        txtEmail.setText("");
        fileLabel.setIcon(null);

        btnThem.setVisible(false);
        btnSua.setVisible(false);
        btnXoa.setVisible(false);
        btnHuy.setVisible(false);
        btnAllowAdd.setVisible(true);
        btnAllowUpdate.setVisible(true);
        btnAllowDelete.setVisible(true);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnAllowAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllowAddActionPerformed
        txtMa.setEditable(true);
        txtTen.setEditable(true);
        txtDiachi.setEditable(true);
        txtSdt.setEditable(true);
        txtEmail.setEditable(true);

        btnThem.setVisible(true);
        btnSua.setVisible(true);
        btnXoa.setVisible(true);
        btnHuy.setVisible(true);
        btnAllowAdd.setVisible(false);
        btnAllowUpdate.setVisible(false);
        btnAllowDelete.setVisible(false);

        btnThem.setEnabled(true);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
    }//GEN-LAST:event_btnAllowAddActionPerformed

    private void btnAllowUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllowUpdateActionPerformed
        txtMa.setEditable(false);
        txtTen.setEditable(true);
        txtDiachi.setEditable(true);
        txtSdt.setEditable(true);
        txtEmail.setEditable(true);

        btnThem.setVisible(true);
        btnSua.setVisible(true);
        btnXoa.setVisible(true);
        btnHuy.setVisible(true);
        btnAllowAdd.setVisible(false);
        btnAllowUpdate.setVisible(false);
        btnAllowDelete.setVisible(false);

        btnSua.setEnabled(true);
        btnThem.setEnabled(false);
        btnXoa.setEnabled(false);
    }//GEN-LAST:event_btnAllowUpdateActionPerformed

    private void btnAllowDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllowDeleteActionPerformed
        txtMa.setEditable(false);
        txtTen.setEditable(true);
        txtDiachi.setEditable(true);
        txtSdt.setEditable(true);
        txtEmail.setEditable(true);

        btnThem.setVisible(true);
        btnSua.setVisible(true);
        btnXoa.setVisible(true);
        btnHuy.setVisible(true);
        btnAllowAdd.setVisible(false);
        btnAllowUpdate.setVisible(false);
        btnAllowDelete.setVisible(false);

        btnXoa.setEnabled(true);
        btnThem.setEnabled(false);
        btnSua.setEnabled(false);
    }//GEN-LAST:event_btnAllowDeleteActionPerformed

    private void tableNccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNccMouseClicked
        int index =  tableNcc.getSelectedRow();
        txtMa.setText((String)(tableModel.getValueAt(index,0)));
        txtTen.setText((String)(tableModel.getValueAt(index,1)));
        txtDiachi.setText((String)(tableModel.getValueAt(index,2)));
        txtSdt.setText((String)(tableModel.getValueAt(index,3)));
        txtEmail.setText((String)(tableModel.getValueAt(index,4)));
        String path = tableModel.getValueAt(index,5).toString();
        ImageIcon ii = new ImageIcon(path);
        Image image = ii.getImage().getScaledInstance(fileLabel.getWidth(), fileLabel.getHeight(), Image.SCALE_SMOOTH);
        fileLabel.setIcon(new ImageIcon(image));

    }//GEN-LAST:event_tableNccMouseClicked

    private void txtSdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSdtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllowAdd;
    private javax.swing.JButton btnAllowDelete;
    private javax.swing.JButton btnAllowUpdate;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnImage;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JTable tableNcc;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
